#!/bin/bash
# ci_post_clone.sh
# Xcode Cloud - Runs after cloning the repository
# Documentation: https://developer.apple.com/documentation/xcode/writing-custom-build-scripts

set -e

echo "=== Echoelmusic Xcode Cloud Post-Clone Script ==="
echo "CI_WORKSPACE: $CI_WORKSPACE"
echo "CI_BRANCH: $CI_BRANCH"
echo "CI_BUILD_NUMBER: $CI_BUILD_NUMBER"

# Navigate to project directory
cd "$CI_WORKSPACE"

# Install any dependencies if needed (e.g., Swift Package Manager)
echo "Resolving Swift Package dependencies..."
swift package resolve || true

# Set build version from Xcode Cloud build number
if [ -n "$CI_BUILD_NUMBER" ]; then
    echo "Setting build number to: $CI_BUILD_NUMBER"
    # This will be used by the Xcode project
    export BUILD_NUMBER=$CI_BUILD_NUMBER
fi

# Create version info file for the app
cat > Sources/Echoelmusic/Core/BuildInfo.generated.swift << EOF
// Auto-generated by Xcode Cloud - Do not edit manually
import Foundation

public enum BuildInfo {
    public static let buildNumber = "$CI_BUILD_NUMBER"
    public static let branch = "$CI_BRANCH"
    public static let commitSHA = "$CI_COMMIT"
    public static let buildDate = "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    public static let isCI = true
}
EOF

echo "=== Post-Clone Complete ==="
