# SwiftLint Configuration for Echoelmusic
# A++++ Quality Standards

# Paths to include
included:
  - Sources
  - Tests

# Paths to exclude
excluded:
  - Sources/DSP          # C++ files
  - Sources/Plugin       # C++ plugin code
  - Sources/UI           # C++ UI code
  - Sources/Desktop      # C++ desktop code
  - Pods
  - Carthage
  - .build
  - build

# Disabled rules
disabled_rules:
  - trailing_whitespace        # Auto-fixed by Xcode
  - line_length                # Handled by custom rule below
  - identifier_name            # Too strict for DSP code
  - type_body_length           # Complex audio classes
  - file_length                # Some files are necessarily long
  - function_body_length       # Audio processing needs long functions
  - cyclomatic_complexity      # State machines are complex

# Opt-in rules for A++++ quality
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Rule configuration
force_cast:
  severity: error

force_try:
  severity: warning

force_unwrapping:
  severity: warning

nesting:
  type_level: 3
  function_level: 5

line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true

function_parameter_count:
  warning: 8
  error: 10

type_name:
  min_length: 2
  max_length: 50

large_tuple:
  warning: 4
  error: 6

vertical_whitespace:
  max_empty_lines: 2

trailing_comma:
  mandatory_comma: false

colon:
  apply_to_dictionaries: true

comma:
  severity: warning

# Custom rules for Echoelmusic
custom_rules:
  no_print_in_production:
    name: "No print in production"
    regex: '^\s*print\('
    message: "Use #if DEBUG or Logger instead of print()"
    severity: warning
    match_kinds:
      - identifier

  audio_thread_safety:
    name: "Audio thread safety"
    regex: 'DispatchQueue\.main\.async.*audio|audio.*DispatchQueue\.main\.async'
    message: "Audio processing should not dispatch to main queue"
    severity: error

  force_unwrap_audio:
    name: "No force unwrap in audio code"
    regex: '(audioBuffer|sampleBuffer|pcmBuffer)!'
    message: "Never force unwrap audio buffers - use guard let"
    severity: error

  # === Echoelmusic-specific build error prevention rules ===

  no_color_magenta:
    name: "Color.magenta does not exist in SwiftUI"
    regex: '(?<![A-Za-z])Color\.magenta'
    message: "Color.magenta doesn't exist. Use Color(red: 1, green: 0, blue: 1) instead."
    severity: error

  no_static_logger_call:
    name: "Logger is instance, not static"
    regex: 'ProfessionalLogger\.log\('
    message: "ProfessionalLogger.log() is an instance method. Use the global 'log' instance: log.log(...)"
    severity: error

  logger_needs_self_in_extension:
    name: "Logger self reference in extension"
    regex: '^\s+log\(\.(debug|info|warning|error|critical)'
    message: "Inside EchoelLogger extensions, use self.log() to avoid calling the global 'log' variable."
    severity: warning

  no_uikit_without_guard:
    name: "UIKit requires canImport guard"
    regex: '^\s*import UIKit\s*$'
    message: "UIKit is iOS-only. Wrap with #if canImport(UIKit) for cross-platform safety."
    severity: warning

  math_log_needs_foundation_prefix:
    name: "Math log() shadowed by logger"
    regex: '(?<!\.)(?<!Foundation\.)(?<!self\.)(?<!Swift\.)log\(\s*[0-9a-zA-Z_]+\s*\)\s*$'
    message: "Math log() is shadowed by the global logger. Use Foundation.log() for logarithm calculations."
    severity: warning

  no_normalized_coherence_arithmetic:
    name: "NormalizedCoherence is not numeric"
    regex: 'coherence\s*[+\-\*\/]\s*[0-9]|[0-9]\s*[+\-\*\/]\s*coherence'
    message: "NormalizedCoherence is not BinaryFloatingPoint. Use .value for arithmetic operations."
    severity: warning

# Reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
reporter: "xcode"
