# =============================================================================
# Echoelmusic - Codemagic CI/CD Configuration (ALTERNATIVE)
# =============================================================================
# NOTE: Primary deployment is via .github/workflows/deploy.yml (GitHub Actions)
# This file is kept as an alternative for those who prefer Codemagic.
#
# Apple (iOS, macOS, watchOS, tvOS, visionOS) + Android
# Windows + Linux → See .github/workflows/desktop_build.yml
# =============================================================================

workflows:
  # ===========================================================================
  # iOS → TestFlight
  # ===========================================================================
  ios:
    name: iOS
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: Echoelmusic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.echoelmusic.app
      vars:
        XCODE_SCHEME: Echoelmusic
        APP_ID: com.echoelmusic.app
        VERSION: "1.1.0"
      xcode: 15.2
    triggering:
      events: [push, tag]
      branch_patterns:
        - pattern: main
          include: true
      tag_patterns:
        - pattern: 'v*'
          include: true
    scripts:
      - name: Install dependencies
        script: swift package resolve
      - name: Get build number
        script: |
          BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "$APP_ID" || echo 0) + 1))
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $CM_ENV
      - name: Build iOS
        script: |
          xcodebuild archive \
            -scheme "$XCODE_SCHEME" \
            -destination "generic/platform=iOS" \
            -archivePath build/iOS.xcarchive \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE=Automatic \
            MARKETING_VERSION="$VERSION" \
            CURRENT_PROJECT_VERSION="$BUILD_NUMBER"
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/iOS.xcarchive \
            -exportPath build/iOS \
            -exportOptionsPlist /dev/stdin <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0"><dict>
            <key>method</key><string>app-store-connect</string>
          </dict></plist>
          EOF
    artifacts:
      - build/iOS/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
    cache:
      cache_paths:
        - $HOME/Library/Caches/org.swift.swiftpm

  # ===========================================================================
  # macOS → TestFlight
  # ===========================================================================
  macos:
    name: macOS
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: Echoelmusic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.echoelmusic.mac
      vars:
        XCODE_SCHEME: Echoelmusic
        VERSION: "1.1.0"
      xcode: 15.2
    triggering:
      events: [push, tag]
      branch_patterns:
        - pattern: main
          include: true
      tag_patterns:
        - pattern: 'v*'
          include: true
    scripts:
      - name: Install dependencies
        script: swift package resolve
      - name: Build macOS
        script: |
          xcodebuild archive \
            -scheme "$XCODE_SCHEME" \
            -destination "generic/platform=macOS" \
            -archivePath build/macOS.xcarchive \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE=Automatic \
            MARKETING_VERSION="$VERSION" \
            CURRENT_PROJECT_VERSION="${BUILD_NUMBER:-1}"
    artifacts:
      - build/macOS/*.pkg
      - build/macOS/*.app
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
    cache:
      cache_paths:
        - $HOME/Library/Caches/org.swift.swiftpm

  # ===========================================================================
  # watchOS → TestFlight (via iOS companion)
  # ===========================================================================
  watchos:
    name: watchOS
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: Echoelmusic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.echoelmusic.app.watchkitapp
      vars:
        VERSION: "1.1.0"
      xcode: 15.2
    triggering:
      events: [tag]
      tag_patterns:
        - pattern: 'v*'
          include: true
    scripts:
      - name: Install dependencies
        script: swift package resolve
      - name: Build watchOS
        script: |
          xcodebuild archive \
            -scheme "Echoelmusic Watch" \
            -destination "generic/platform=watchOS" \
            -archivePath build/watchOS.xcarchive \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE=Automatic \
            MARKETING_VERSION="$VERSION" \
            CURRENT_PROJECT_VERSION="${BUILD_NUMBER:-1}"
    artifacts:
      - build/watchOS/*.xcarchive
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  # ===========================================================================
  # tvOS → TestFlight
  # ===========================================================================
  tvos:
    name: tvOS
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: Echoelmusic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.echoelmusic.tv
      vars:
        XCODE_SCHEME: Echoelmusic
        VERSION: "1.1.0"
      xcode: 15.2
    triggering:
      events: [tag]
      tag_patterns:
        - pattern: 'v*'
          include: true
    scripts:
      - name: Install dependencies
        script: swift package resolve
      - name: Build tvOS
        script: |
          xcodebuild archive \
            -scheme "$XCODE_SCHEME" \
            -destination "generic/platform=tvOS" \
            -archivePath build/tvOS.xcarchive \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE=Automatic \
            MARKETING_VERSION="$VERSION" \
            CURRENT_PROJECT_VERSION="${BUILD_NUMBER:-1}"
    artifacts:
      - build/tvOS/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  # ===========================================================================
  # visionOS → TestFlight
  # ===========================================================================
  visionos:
    name: visionOS
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: Echoelmusic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.echoelmusic.vision
      vars:
        XCODE_SCHEME: Echoelmusic
        VERSION: "1.1.0"
      xcode: 15.2
    triggering:
      events: [tag]
      tag_patterns:
        - pattern: 'v*'
          include: true
    scripts:
      - name: Install dependencies
        script: swift package resolve
      - name: Build visionOS
        script: |
          xcodebuild archive \
            -scheme "$XCODE_SCHEME" \
            -destination "generic/platform=visionOS" \
            -archivePath build/visionOS.xcarchive \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE=Automatic \
            MARKETING_VERSION="$VERSION" \
            CURRENT_PROJECT_VERSION="${BUILD_NUMBER:-1}"
    artifacts:
      - build/visionOS/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  # ===========================================================================
  # Android → Play Store (Internal Testing)
  # ===========================================================================
  android:
    name: Android
    instance_type: linux_x2
    max_build_duration: 60
    environment:
      java: 17
      vars:
        VERSION: "1.1.0"
    triggering:
      events: [push, tag]
      branch_patterns:
        - pattern: main
          include: true
      tag_patterns:
        - pattern: 'v*'
          include: true
    scripts:
      - name: Set version
        script: |
          cd android
          sed -i "s/versionCode = [0-9]*/versionCode = $BUILD_NUMBER/" app/build.gradle.kts 2>/dev/null || true
          sed -i "s/versionName = \"[^\"]*\"/versionName = \"$VERSION\"/" app/build.gradle.kts 2>/dev/null || true
      - name: Build
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease bundleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - android/.gradle
