# XcodeGen Project Configuration for Echoelmusic
# This file defines how to generate the Xcode project

name: Echoelmusic

options:
  bundleIdPrefix: com.echoelmusic
  # Use Xcode 15.4 format for GitHub Actions compatibility (macos-14 runner)
  xcodeVersion: "15.4"
  deploymentTarget:
    iOS: "16.0"      # Wide compatibility (iPhone 8+)
    macOS: "13.0"    # macOS Ventura+
    watchOS: "9.0"   # Apple Watch Series 4+
    tvOS: "16.0"     # Apple TV HD+
    visionOS: "1.0"  # Vision Pro
  # Generate Info.plist automatically
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    PRODUCT_NAME: $(TARGET_NAME)
    MARKETING_VERSION: "1.2.0"
    CURRENT_PROJECT_VERSION: "${BUILD_NUMBER:=1}"

targets:
  Echoelmusic:
    type: application
    platform: iOS

    # Source files location
    sources:
      - path: Sources/Echoelmusic
        type: group
        excludes:
          - "**/*.xcassets"

    # Resources
    resources:
      - path: Sources/Echoelmusic/Resources/Assets.xcassets
        type: folder
      - path: PrivacyInfo.xcprivacy
        type: file

    # Info.plist configuration (inline)
    info:
      path: Resources/iOS/Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleDisplayName: Echoelmusic
        LSRequiresIPhoneOS: true

        # Permissions
        NSMicrophoneUsageDescription: "Echoelmusic needs microphone access to create music from your voice and breath"
        NSHealthShareUsageDescription: "Echoelmusic uses heart rate data to create bio-reactive music that responds to your body"
        NSHealthUpdateUsageDescription: "Echoelmusic can save your coherence scores to Health"
        NSBluetoothAlwaysUsageDescription: "Echoelmusic connects to Bluetooth MIDI controllers and audio devices"
        NSBluetoothPeripheralUsageDescription: "Echoelmusic connects to Bluetooth audio devices for ultra-low latency monitoring"
        NSCameraUsageDescription: "Echoelmusic uses your camera for face tracking to control audio parameters with facial expressions"
        NSFaceIDUsageDescription: "Echoelmusic uses TrueDepth camera for face tracking to map expressions to audio-visual parameters"
        NSMotionUsageDescription: "Echoelmusic uses motion data for gesture-based audio control and spatial audio head tracking"
        NSLocalNetworkUsageDescription: "Echoelmusic uses local network for DMX lighting control, Art-Net, and connecting to external audio interfaces"
        NSBonjourServices:
          - "_http._tcp"
          - "_rtsp._tcp"
          - "_artnet._udp"
          - "_osc._udp"
          - "_midi._udp"
          - "_echoelmusic._tcp"

        # Export compliance
        ITSAppUsesNonExemptEncryption: false

        # Background modes
        UIBackgroundModes:
          - audio
          - bluetooth-central

        # UI Configuration
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIUserInterfaceStyle: Dark
        UIRequiresFullScreen: false

        # SwiftUI support - no SceneDelegate needed with @main App
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false

    # App settings
    settings:
      base:
        PRODUCT_NAME: Echoelmusic
        PRODUCT_BUNDLE_IDENTIFIER: com.echoelmusic.app
        INFOPLIST_FILE: Resources/iOS/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        CODE_SIGN_ENTITLEMENTS: Echoelmusic.entitlements

        # Code signing (for CI/CD automatic signing)
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: ""

        # Build settings
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
        SWIFT_VERSION: "5.9"
        ENABLE_BITCODE: NO
        ALWAYS_SEARCH_USER_PATHS: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

    # Dependencies (AUv3 extension temporarily disabled for CI)
    # dependencies:
    #   - target: EchoelmusicAUv3
    #     embed: true

    # Entitlements for App Store
    entitlements:
      path: Echoelmusic.entitlements

  # ===========================================
  # AUv3 Audio Unit Extension
  # ===========================================
  EchoelmusicAUv3:
    type: app-extension
    platform: iOS

    # Source files
    sources:
      - path: Sources/EchoelmusicAUv3
        type: group
      - path: Sources/Echoelmusic/Sound/TR808BassSynth.swift
        type: file

    # Info.plist
    info:
      path: Sources/EchoelmusicAUv3/Info.plist

    # Extension settings
    settings:
      base:
        PRODUCT_NAME: EchoelmusicAUv3
        PRODUCT_BUNDLE_IDENTIFIER: com.echoelmusic.app.auv3
        INFOPLIST_FILE: Sources/EchoelmusicAUv3/Info.plist
        GENERATE_INFOPLIST_FILE: NO

        # Code signing
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_ENTITLEMENTS: Sources/EchoelmusicAUv3/EchoelmusicAUv3.entitlements

        # Build settings
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
        SWIFT_VERSION: "5.9"
        ENABLE_BITCODE: NO

        # Extension settings
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
        SKIP_INSTALL: YES

    # Frameworks
    dependencies:
      - framework: AudioToolbox.framework
      - framework: AVFoundation.framework
      - framework: CoreAudioKit.framework
      - framework: Accelerate.framework

  # ===========================================
  # Unit Tests
  # ===========================================
  EchoelmusicTests:
    type: bundle.unit-test
    platform: iOS

    sources:
      - path: Tests/EchoelmusicTests
        type: group

    dependencies:
      - target: Echoelmusic

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.echoelmusic.tests
        SWIFT_VERSION: "5.9"
