# XcodeGen Project Configuration for Echoelmusic
# Multi-Platform Audio/Video Production Suite
# Supports: iOS, iPadOS, macOS, watchOS, tvOS, visionOS

name: Echoelmusic

options:
  bundleIdPrefix: com.echoelmusic
  deploymentTarget:
    iOS: "15.0"
    macOS: "12.0"
    watchOS: "8.0"
    tvOS: "15.0"
    visionOS: "1.0"
  generateEmptyDirectories: true
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    PRODUCT_NAME: $(TARGET_NAME)
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    ENABLE_BITCODE: NO
    CODE_SIGN_STYLE: Automatic

# ====================
# TARGETS
# ====================

targets:
  # -------------------- iOS/iPadOS App --------------------
  Echoelmusic-iOS:
    type: application
    platform: iOS

    sources:
      - path: Sources/Echoelmusic
        excludes:
          - "**/*macOS*.swift"
          - "**/*watchOS*.swift"
          - "**/*tvOS*.swift"
          - "**/*visionOS*.swift"

    settings:
      base:
        PRODUCT_NAME: Echoelmusic
        PRODUCT_BUNDLE_IDENTIFIER: com.echoelmusic.studio
        TARGETED_DEVICE_FAMILY: "1,2"  # iPhone + iPad
        IPHONEOS_DEPLOYMENT_TARGET: "15.0"
        SUPPORTS_MACCATALYST: YES
        DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: YES

    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: Echoelmusic
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSRequiresIPhoneOS: true
        UIUserInterfaceStyle: Dark
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSMicrophoneUsageDescription: "Echoelmusic needs microphone access for audio recording and music creation"
        NSCameraUsageDescription: "Echoelmusic needs camera access for video recording and live streaming"
        NSPhotoLibraryUsageDescription: "Echoelmusic needs photo library access to export videos and images"
        NSHealthShareUsageDescription: "Echoelmusic uses heart rate data for bio-reactive music"
        NSHealthUpdateUsageDescription: "Echoelmusic records coherence data to HealthKit"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true

  # -------------------- macOS App --------------------
  Echoelmusic-macOS:
    type: application
    platform: macOS

    sources:
      - path: Sources/Echoelmusic
        excludes:
          - "**/*iOS*.swift"
          - "**/*watchOS*.swift"
          - "**/*tvOS*.swift"
          - "**/*visionOS*.swift"

    settings:
      base:
        PRODUCT_NAME: Echoelmusic
        PRODUCT_BUNDLE_IDENTIFIER: com.echoelmusic.studio.mac
        MACOSX_DEPLOYMENT_TARGET: "12.0"
        ENABLE_HARDENED_RUNTIME: YES
        COMBINE_HIDPI_IMAGES: YES

    info:
      path: Info-macOS.plist
      properties:
        CFBundleDisplayName: Echoelmusic Pro
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        NSMicrophoneUsageDescription: "Echoelmusic needs microphone access for professional audio recording"
        NSCameraUsageDescription: "Echoelmusic needs camera access for professional video production"
        NSPrincipalClass: NSApplication
        NSHighResolutionCapable: true

  # -------------------- watchOS App --------------------
  Echoelmusic-watchOS:
    type: application
    platform: watchOS

    sources:
      - path: Sources/Echoelmusic/watchOS

    settings:
      base:
        PRODUCT_NAME: Echoelmusic
        PRODUCT_BUNDLE_IDENTIFIER: com.echoelmusic.studio.watchos
        WATCHOS_DEPLOYMENT_TARGET: "8.0"
        TARGETED_DEVICE_FAMILY: "4"

    info:
      path: Info-watchOS.plist
      properties:
        CFBundleDisplayName: Echoelmusic
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        WKWatchOnly: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait

  # -------------------- tvOS App --------------------
  Echoelmusic-tvOS:
    type: application
    platform: tvOS

    sources:
      - path: Sources/Echoelmusic
        excludes:
          - "**/*iOS*.swift"
          - "**/*macOS*.swift"
          - "**/*watchOS*.swift"
          - "**/*visionOS*.swift"
          - "**/Biofeedback/**"  # No HealthKit on tvOS

    settings:
      base:
        PRODUCT_NAME: Echoelmusic
        PRODUCT_BUNDLE_IDENTIFIER: com.echoelmusic.studio.tv
        TVOS_DEPLOYMENT_TARGET: "15.0"
        TARGETED_DEVICE_FAMILY: "3"

    info:
      path: Info-tvOS.plist
      properties:
        CFBundleDisplayName: Echoelmusic
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        UIUserInterfaceStyle: Dark

  # -------------------- visionOS App --------------------
  Echoelmusic-visionOS:
    type: application
    platform: visionOS

    sources:
      - path: Sources/Echoelmusic
        excludes:
          - "**/*iOS*.swift"
          - "**/*macOS*.swift"
          - "**/*watchOS*.swift"
          - "**/*tvOS*.swift"

    settings:
      base:
        PRODUCT_NAME: Echoelmusic
        PRODUCT_BUNDLE_IDENTIFIER: com.echoelmusic.studio.vision
        XROS_DEPLOYMENT_TARGET: "1.0"
        TARGETED_DEVICE_FAMILY: "7"  # visionOS

    info:
      path: Info-visionOS.plist
      properties:
        CFBundleDisplayName: Echoelmusic Spatial
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSMicrophoneUsageDescription: "Echoelmusic needs microphone access for spatial audio recording"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
          UIApplicationPreferredDefaultSceneSessionRole: UIWindowSceneSessionRoleImmersiveSpaceApplication
