//
//  DAWExportManager.swift
//  EchoelCalculator
//
//  Export scientific timing data to DAWs (Reaper, Ableton, Logic, etc.)
//

import Foundation

/// Export manager for Digital Audio Workstations
public class DAWExportManager {

    // MARK: - Reaper RPP Export

    /// Export to Reaper RPP project format with scientific markers
    public static func exportToReaper(
        _ output: ScientificEchoelCalculator.CalculatorOutput,
        duration: TimeInterval,
        projectName: String = "EchoelSync"
    ) -> String {

        var rpp = ""

        // Project header
        rpp += "<REAPER_PROJECT 0.1 \"6.0\"\n"
        rpp += "  NAME \"\(projectName)\"\n"
        rpp += "  TEMPO \(output.bpm) 4 4\n"
        rpp += "  SAMPLERATE 48000 0 0\n"
        rpp += "\n"

        // Add metadata track
        rpp += "  <TRACK {METADATA-TRACK}\n"
        rpp += "    NAME \"EchoelSync Metadata\"\n"
        rpp += "    NOTES \"Generated by Scientific EchoelCalculator\\n"
        rpp += "Brainwave: \(output.dominantBrainwave.name) (\(String(format: "%.1f", output.entrainmentFrequency)) Hz)\\n"
        rpp += "Cognitive Effect: \(output.cognitiveEffect)\\n"
        rpp += "p-value: \(output.dominantBrainwave.pValue)\\n"
        rpp += "Effect Size: \(output.dominantBrainwave.effectSize)\"\n"
        rpp += "  >\n"

        // Add markers at beat positions with scientific annotations
        var time: Double = 0
        var markerNum = 1
        var beatCount = 0

        while time < duration {
            let markerType: String
            let markerColor: String
            let markerName: String

            // Beat position
            beatCount += 1

            // Color-code by brainwave type
            switch output.dominantBrainwave.name {
            case "Delta":
                markerColor = "16711680"  // Blue (RGB: 0,0,255)
            case "Theta":
                markerColor = "8388736"   // Purple (RGB: 128,0,128)
            case "Alpha":
                markerColor = "65280"     // Green (RGB: 0,255,0)
            case "Beta":
                markerColor = "16776960"  // Yellow (RGB: 255,255,0)
            case "Gamma", "40Hz Gamma (MIT)":
                markerColor = "16711680"  // Red (RGB: 255,0,0)
            default:
                markerColor = "8421504"   // Gray
            }

            // Mark important beats
            if beatCount % 4 == 1 {
                markerName = "Beat \(beatCount) - \(output.dominantBrainwave.name) Peak"
                markerType = "1"  // Region start
            } else {
                markerName = "Beat \(beatCount)"
                markerType = "0"  // Regular marker
            }

            rpp += "  MARKER \(markerNum) \(time) \"\(markerName)\" \(markerType) \(markerColor) 1 B\n"

            markerNum += 1
            time += Double(output.msDelay) / 1000.0
        }

        // Add region for entrainment
        rpp += "  <MARKER {ENTRAINMENT-REGION}\n"
        rpp += "    RGNS 1 \(duration) \"Entrainment Region - \(output.dominantBrainwave.name)\" 0 16711680\n"
        rpp += "    NOTES \"Frequency: \(String(format: "%.2f", output.entrainmentFrequency)) Hz\\n"
        rpp += "Effect: \(output.cognitiveEffect)\\n"
        rpp += "Reference: \(output.dominantBrainwave.reference)\"\n"
        rpp += "  >\n"

        rpp += ">\n"

        return rpp
    }

    // MARK: - Ableton Live Set Export

    /// Export to Ableton Live Set format (ALS - XML based)
    public static func exportToAbleton(
        _ output: ScientificEchoelCalculator.CalculatorOutput,
        duration: TimeInterval
    ) -> String {

        var als = ""

        // Ableton Live Set XML header
        als += "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
        als += "<Ableton MajorVersion=\"5\" MinorVersion=\"11.0_432\" Creator=\"EchoelCalculator\">\n"
        als += "  <LiveSet>\n"

        // Tempo automation
        als += "    <MasterTrack>\n"
        als += "      <Tempo>\n"
        als += "        <Manual Value=\"\(output.bpm)\" />\n"
        als += "      </Tempo>\n"
        als += "    </MasterTrack>\n"

        // Locators for beats
        als += "    <Locators>\n"

        var time: Double = 0
        var beatCount = 0

        while time < duration {
            beatCount += 1

            als += "      <Locator Id=\"\(beatCount)\" Time=\"\(time)\">\n"
            als += "        <Name Value=\"Beat \(beatCount) - \(output.dominantBrainwave.name)\" />\n"
            als += "      </Locator>\n"

            time += Double(output.msDelay) / 1000.0
        }

        als += "    </Locators>\n"

        // Metadata
        als += "    <Annotation Value=\""
        als += "EchoelSync Project\\n"
        als += "Brainwave: \(output.dominantBrainwave.name) (\(String(format: "%.1f", output.entrainmentFrequency)) Hz)\\n"
        als += "Cognitive Effect: \(output.cognitiveEffect)\\n"
        als += "Statistical Significance: p &lt; \(output.dominantBrainwave.pValue)\\n"
        als += "Effect Size: d = \(output.dominantBrainwave.effectSize)\\n"
        als += "Reference: \(output.dominantBrainwave.reference)"
        als += "\" />\n"

        als += "  </LiveSet>\n"
        als += "</Ableton>\n"

        return als
    }

    // MARK: - Logic Pro X Export

    /// Export to Logic Pro X compatible format (MIDI with markers)
    public static func exportToLogicPro(
        _ output: ScientificEchoelCalculator.CalculatorOutput,
        duration: TimeInterval
    ) -> Data {

        // Logic Pro uses Standard MIDI File format with marker meta events
        var midiData = Data()

        // MIDI Header
        midiData.append(contentsOf: [0x4D, 0x54, 0x68, 0x64])  // "MThd"
        midiData.append(contentsOf: [0x00, 0x00, 0x00, 0x06])  // Header length
        midiData.append(contentsOf: [0x00, 0x01])              // Format 1
        midiData.append(contentsOf: [0x00, 0x02])              // 2 tracks
        midiData.append(contentsOf: [0x01, 0xE0])              // 480 ticks/quarter

        // Track 1: Tempo & Metadata
        var track1 = Data()

        // Tempo event
        let microsecondsPerQuarter = UInt32(60000000.0 / output.bpm)
        track1.append(contentsOf: [0x00, 0xFF, 0x51, 0x03])  // Delta time + tempo meta event
        track1.append(UInt8((microsecondsPerQuarter >> 16) & 0xFF))
        track1.append(UInt8((microsecondsPerQuarter >> 8) & 0xFF))
        track1.append(UInt8(microsecondsPerQuarter & 0xFF))

        // Text event with scientific info
        let infoText = "EchoelSync: \(output.dominantBrainwave.name) (\(String(format: "%.1f", output.entrainmentFrequency)) Hz)"
        let infoTextData = infoText.data(using: .ascii) ?? Data()
        track1.append(contentsOf: [0x00, 0xFF, 0x01])
        track1.append(UInt8(infoTextData.count))
        track1.append(infoTextData)

        // End of track
        track1.append(contentsOf: [0x00, 0xFF, 0x2F, 0x00])

        // Write track 1
        midiData.append(contentsOf: [0x4D, 0x54, 0x72, 0x6B])  // "MTrk"
        let track1Length = UInt32(track1.count)
        midiData.append(UInt8((track1Length >> 24) & 0xFF))
        midiData.append(UInt8((track1Length >> 16) & 0xFF))
        midiData.append(UInt8((track1Length >> 8) & 0xFF))
        midiData.append(UInt8(track1Length & 0xFF))
        midiData.append(track1)

        // Track 2: Markers
        var track2 = Data()

        var time: Double = 0
        var beatCount = 0
        let ticksPerBeat = 480

        while time < duration {
            beatCount += 1

            // Marker event
            let markerText = "Beat \(beatCount) - \(output.dominantBrainwave.name)"
            let markerData = markerText.data(using: .ascii) ?? Data()

            let deltaTime = beatCount == 1 ? 0 : ticksPerBeat
            track2.append(UInt8(deltaTime))
            track2.append(contentsOf: [0xFF, 0x06])  // Marker meta event
            track2.append(UInt8(markerData.count))
            track2.append(markerData)

            time += Double(output.msDelay) / 1000.0
        }

        // End of track
        track2.append(contentsOf: [0x00, 0xFF, 0x2F, 0x00])

        // Write track 2
        midiData.append(contentsOf: [0x4D, 0x54, 0x72, 0x6B])  // "MTrk"
        let track2Length = UInt32(track2.count)
        midiData.append(UInt8((track2Length >> 24) & 0xFF))
        midiData.append(UInt8((track2Length >> 16) & 0xFF))
        midiData.append(UInt8((track2Length >> 8) & 0xFF))
        midiData.append(UInt8(track2Length & 0xFF))
        midiData.append(track2)

        return midiData
    }

    // MARK: - Generic CSV Export

    /// Export to CSV for any DAW (universal format)
    public static func exportToCSV(
        _ output: ScientificEchoelCalculator.CalculatorOutput,
        duration: TimeInterval
    ) -> String {

        var csv = "Time (s),Beat Number,Brainwave,Frequency (Hz),Cognitive Effect,Note\n"

        var time: Double = 0
        var beatCount = 0

        while time < duration {
            beatCount += 1

            csv += String(format: "%.3f", time)
            csv += ",\(beatCount)"
            csv += ",\(output.dominantBrainwave.name)"
            csv += ",\(String(format: "%.2f", output.entrainmentFrequency))"
            csv += ",\"\(output.cognitiveEffect)\""
            csv += ",\(output.noteName)\n"

            time += Double(output.msDelay) / 1000.0
        }

        return csv
    }

    // MARK: - File Writing

    /// Save export to file
    public static func saveToFile(content: String, filename: String) throws {
        let url = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
            .appendingPathComponent(filename)

        try content.write(to: url, atomically: true, encoding: .utf8)
    }

    /// Save binary data to file
    public static func saveDataToFile(data: Data, filename: String) throws {
        let url = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
            .appendingPathComponent(filename)

        try data.write(to: url)
    }
}
