# =============================================================================
# REUSABLE ACTION: Setup XcodeGen with Caching
# =============================================================================
# Installs XcodeGen via direct download with caching for faster CI runs.
# Saves ~30-40 seconds per job compared to brew install.
# =============================================================================

name: 'Setup XcodeGen'
description: 'Install XcodeGen with caching for faster CI builds'

inputs:
  version:
    description: 'XcodeGen version to install'
    required: false
    default: '2.42.0'

runs:
  using: 'composite'
  steps:
    - name: Cache XcodeGen
      id: cache-xcodegen
      uses: actions/cache@v4
      with:
        path: ~/xcodegen-bin
        key: xcodegen-${{ runner.os }}-${{ inputs.version }}-v2

    - name: Install XcodeGen
      if: steps.cache-xcodegen.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -e
        echo "Installing XcodeGen ${{ inputs.version }}..."

        # Create cache directory
        mkdir -p ~/xcodegen-bin

        # Download with progress and error handling
        DOWNLOAD_URL="https://github.com/yonaskolb/XcodeGen/releases/download/${{ inputs.version }}/xcodegen.zip"
        echo "Downloading from: $DOWNLOAD_URL"

        if ! curl -fL "$DOWNLOAD_URL" -o /tmp/xcodegen.zip; then
          echo "ERROR: Failed to download XcodeGen ${{ inputs.version }}"
          exit 1
        fi

        # Verify download
        if [ ! -s /tmp/xcodegen.zip ]; then
          echo "ERROR: Downloaded file is empty"
          exit 1
        fi

        # Verify ZIP integrity before extracting
        echo "Verifying ZIP integrity..."
        if ! unzip -t /tmp/xcodegen.zip > /dev/null 2>&1; then
          echo "ERROR: ZIP file is corrupted"
          rm -f /tmp/xcodegen.zip
          exit 1
        fi

        # Extract to dedicated directory
        echo "Extracting..."
        EXTRACT_DIR="/tmp/xcodegen-extract-$$"
        mkdir -p "$EXTRACT_DIR"
        unzip -o /tmp/xcodegen.zip -d "$EXTRACT_DIR"

        # Debug: show extracted contents
        echo "Extracted contents:"
        ls -la "$EXTRACT_DIR"

        # Find xcodegen binary - check multiple possible locations
        XCODEGEN_BIN=""
        for possible_path in \
          "$EXTRACT_DIR/xcodegen/bin/xcodegen" \
          "$EXTRACT_DIR/XcodeGen/bin/xcodegen" \
          "$EXTRACT_DIR/bin/xcodegen" \
          "$EXTRACT_DIR/xcodegen"; do
          if [ -f "$possible_path" ]; then
            XCODEGEN_BIN="$possible_path"
            echo "Found xcodegen at: $XCODEGEN_BIN"
            break
          fi
        done

        if [ -z "$XCODEGEN_BIN" ]; then
          echo "ERROR: Could not find xcodegen binary"
          echo "Searching recursively..."
          find "$EXTRACT_DIR" -name "xcodegen" -type f 2>/dev/null || true
          exit 1
        fi

        # Move to cache location
        cp "$XCODEGEN_BIN" ~/xcodegen-bin/
        chmod +x ~/xcodegen-bin/xcodegen

        # Cleanup
        rm -rf "$EXTRACT_DIR" /tmp/xcodegen.zip

        echo "XcodeGen installed to ~/xcodegen-bin/"

    - name: Add to PATH
      shell: bash
      run: |
        echo "$HOME/xcodegen-bin" >> $GITHUB_PATH
        echo "Added ~/xcodegen-bin to PATH"

    - name: Verify XcodeGen
      shell: bash
      run: |
        echo "Verifying XcodeGen installation..."
        which xcodegen || echo "xcodegen not in PATH, checking cache..."
        ~/xcodegen-bin/xcodegen --version
