# =============================================================================
# REUSABLE ACTION: Setup XcodeGen with Caching
# =============================================================================
# Installs XcodeGen via direct download with caching for faster CI runs.
# Saves ~30-40 seconds per job compared to brew install.
# =============================================================================

name: 'Setup XcodeGen'
description: 'Install XcodeGen with caching for faster CI builds'

inputs:
  version:
    description: 'XcodeGen version to install'
    required: false
    default: '2.42.0'

runs:
  using: 'composite'
  steps:
    - name: Cache XcodeGen
      id: cache-xcodegen
      uses: actions/cache@v4
      with:
        path: ~/xcodegen-bin
        key: xcodegen-${{ runner.os }}-${{ inputs.version }}-v2

    - name: Install XcodeGen
      if: steps.cache-xcodegen.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -e
        echo "Installing XcodeGen ${{ inputs.version }}..."

        # Create cache directory
        mkdir -p ~/xcodegen-bin

        # Download with progress and error handling
        DOWNLOAD_URL="https://github.com/yonaskolb/XcodeGen/releases/download/${{ inputs.version }}/xcodegen.zip"
        echo "Downloading from: $DOWNLOAD_URL"

        if ! curl -fL "$DOWNLOAD_URL" -o /tmp/xcodegen.zip; then
          echo "ERROR: Failed to download XcodeGen ${{ inputs.version }}"
          exit 1
        fi

        # Verify download
        if [ ! -s /tmp/xcodegen.zip ]; then
          echo "ERROR: Downloaded file is empty"
          exit 1
        fi

        # Verify ZIP integrity before extracting
        echo "Verifying ZIP integrity..."
        if ! unzip -t /tmp/xcodegen.zip > /dev/null 2>&1; then
          echo "ERROR: ZIP file is corrupted"
          rm -f /tmp/xcodegen.zip
          exit 1
        fi

        # Extract
        echo "Extracting..."
        unzip -o /tmp/xcodegen.zip -d /tmp

        # Find the extracted directory (could be XcodeGen or xcodegen)
        XCODEGEN_DIR=$(find /tmp -maxdepth 1 -type d -iname "xcodegen*" | head -1)
        echo "Found XcodeGen directory: $XCODEGEN_DIR"

        if [ -z "$XCODEGEN_DIR" ] || [ ! -f "$XCODEGEN_DIR/bin/xcodegen" ]; then
          echo "ERROR: Could not find xcodegen binary in extracted files"
          ls -la /tmp/
          exit 1
        fi

        # Move to cache location
        cp "$XCODEGEN_DIR/bin/xcodegen" ~/xcodegen-bin/
        chmod +x ~/xcodegen-bin/xcodegen

        # Cleanup
        rm -rf /tmp/xcodegen /tmp/xcodegen.zip

        echo "XcodeGen installed to ~/xcodegen-bin/"

    - name: Add to PATH
      shell: bash
      run: |
        echo "$HOME/xcodegen-bin" >> $GITHUB_PATH
        echo "Added ~/xcodegen-bin to PATH"

    - name: Verify XcodeGen
      shell: bash
      run: |
        echo "Verifying XcodeGen installation..."
        which xcodegen || echo "xcodegen not in PATH, checking cache..."
        ~/xcodegen-bin/xcodegen --version
