//
//  PluginWrapper.swift
//  EchoelmusicAUv3
//
//  macOS Plugin Format Wrapper
//  Bridges Echoelmusic's shared DSP core to non-Apple plugin formats
//
//  ┌──────────────────────────────────────────────────────┐
//  │           Shared DSP Core (EchoelmusicDSPKernel)     │
//  │                        │                              │
//  │   ┌────────┬───────────┼───────────┬──────────┐      │
//  │   │        │           │           │          │      │
//  │  AUv3    VST3        CLAP        AAX      Standalone │
//  │ (Apple) (Steinberg) (free-audio) (Avid)   (macOS)   │
//  └──────────────────────────────────────────────────────┘
//
//  Build targets (macOS only, via CMake):
//    cmake .. -DBUILD_VST3=ON -DBUILD_CLAP=ON -DBUILD_AAX=OFF
//
//  AUv3 is always built via SPM/Xcode (Info.plist registration).
//  VST3/CLAP use the C++ DSP bridge in Desktop/PluginBridge.cpp.
//

#if os(macOS)

import Foundation

// MARK: - Plugin Format Registry

/// Supported plugin formats on macOS
public enum EchoelPluginFormat: String, CaseIterable {
    case auv3 = "AUv3"           // Apple Audio Unit v3 (all Apple platforms)
    case vst3 = "VST3"           // Steinberg VST3 (macOS, Windows, Linux)
    case clap = "CLAP"           // CLever Audio Plugin (macOS, Windows, Linux)
    case standalone = "Standalone" // macOS standalone app

    var fileExtension: String {
        switch self {
        case .auv3:       return "appex"
        case .vst3:       return "vst3"
        case .clap:       return "clap"
        case .standalone: return "app"
        }
    }

    var installPath: String {
        switch self {
        case .auv3:       return "~/Library/Audio/Plug-Ins/Components/"
        case .vst3:       return "~/Library/Audio/Plug-Ins/VST3/"
        case .clap:       return "~/Library/Audio/Plug-Ins/CLAP/"
        case .standalone: return "/Applications/"
        }
    }

    var isNativeApple: Bool {
        return self == .auv3 || self == .standalone
    }
}

// MARK: - Plugin Manifest

/// Registry of all 10 Echoel* plugins and their format availability
public struct EchoelPluginManifest {

    public struct PluginEntry {
        public let id: EchoelPluginID
        public let formats: [EchoelPluginFormat]
        public let category: PluginCategory

        public enum PluginCategory: String {
            case instrument = "Instrument"
            case effect = "Effect"
            case midiProcessor = "MIDI Processor"
        }
    }

    /// All 10 Echoel* plugins with supported formats
    public static let plugins: [PluginEntry] = [
        // Instruments — AUv3 + VST3 + CLAP + Standalone
        PluginEntry(id: .echoelSynth, formats: [.auv3, .vst3, .clap, .standalone], category: .instrument),
        PluginEntry(id: .echoelBio,   formats: [.auv3, .vst3, .clap, .standalone], category: .instrument),

        // Effects — AUv3 + VST3 + CLAP
        PluginEntry(id: .echoelFX,    formats: [.auv3, .vst3, .clap], category: .effect),
        PluginEntry(id: .echoelMix,   formats: [.auv3, .vst3, .clap], category: .effect),
        PluginEntry(id: .echoelField, formats: [.auv3, .vst3, .clap], category: .effect),
        PluginEntry(id: .echoelMind,  formats: [.auv3, .vst3, .clap], category: .effect),

        // MIDI Processors — AUv3 + CLAP (VST3 MIDI-only is limited)
        PluginEntry(id: .echoelSeq,   formats: [.auv3, .clap], category: .midiProcessor),
        PluginEntry(id: .echoelMIDI,  formats: [.auv3, .clap], category: .midiProcessor),
        PluginEntry(id: .echoelBeam,  formats: [.auv3, .clap], category: .midiProcessor),
        PluginEntry(id: .echoelNet,   formats: [.auv3, .clap], category: .midiProcessor),
    ]

    /// Get all plugins for a given format
    public static func plugins(for format: EchoelPluginFormat) -> [PluginEntry] {
        return plugins.filter { $0.formats.contains(format) }
    }
}

// MARK: - VST3/CLAP Build Configuration

/// CMake configuration for building non-Apple plugin formats
/// Generated by: cmake .. -DBUILD_VST3=ON -DBUILD_CLAP=ON
///
/// The C++ bridge lives in Desktop/PluginBridge.cpp and wraps
/// the same DSP kernels used by AUv3 via a C-compatible interface:
///
///   extern "C" {
///     void* echoelmusic_create_plugin(const char* plugin_id);
///     void  echoelmusic_process(void* ctx, float** in, float** out, int frames);
///     void  echoelmusic_set_parameter(void* ctx, uint32_t id, float value);
///     float echoelmusic_get_parameter(void* ctx, uint32_t id);
///     void  echoelmusic_handle_midi(void* ctx, uint8_t status, uint8_t d1, uint8_t d2);
///     void  echoelmusic_destroy_plugin(void* ctx);
///   }
///
/// This C bridge is consumed by:
///   - Desktop/VST3Wrapper.cpp  (Steinberg VST3 SDK wrapper)
///   - Desktop/CLAPWrapper.cpp  (CLAP API wrapper)
public enum EchoelPluginBuildConfig {
    public static let vst3SDKMinVersion = "3.7.9"
    public static let clapAPIMinVersion = "1.2.0"
    public static let manufacturerID = "Echo"  // 4-char code
    public static let vendorName = "Echoelmusic"
    public static let vendorURL = "https://echoelmusic.com"
}

#endif
